#!/usr/bin/env python3
"""
run_af_fd_nio.py — run an AgentFlake NIO container end-to-end through FlakyDoctor + Claude.

The NIO analog of run_af_fd_id.py. It reuses run_af_fd's staging / build / maven helpers
verbatim, but swaps the ID-specific parts for NIO (Non-Idempotent-Outcome):

  1. select the `nio` row from test_config.csv (by result_container name)
  2. stage the Zenodo zip into projects/<zipbase>/<project>/  (reuses run_af_fd)
  3. git-init a baseline commit                               (reuses run_af_fd)
  4. generate the twice-in-one-JVM JUnit wrapper next to the victim (untracked, so it
     survives FlakyDoctor's between-round git restores)
  5. build with the container's pre-staged .m2                (reuses run_af_fd)
  6. DETERMINISTICALLY reproduce the NIO flake by running the wrapper (victim twice in one
     JVM); gated on the wrapper test FAILING (the 2nd invocation fails). Zero API cost.
  7. run flakydoctor.py --flakiness-type NIO --model Claude   (unless --skip-repair)
  8. summarize.

A NIO test passes the first time but fails when run again in the same JVM because it leaves
shared state behind. There is no polluter (OD) and no NonDex seed (ID); the wrapper that
invokes the victim twice is the reproduction/verification oracle. The victim test method
remains the only repair target.

Usage (from the FlakyDoctor root):
  python3 src/run_af_fd_nio.py \
      --container quickcheckc1c1 \
      --api-key "$(cat .anthropic_api_key)"

  python3 src/run_af_fd_nio.py --list
  python3 src/run_af_fd_nio.py --container X --skip-repair   # reproduce only
"""

import argparse
import csv
import json
import os
import re
import subprocess
import sys
import time

import run_af_fd as rf  # reuse stage_container/build_project/maven_env/ensure_git_baseline/...

# Mirror run_surefire.sh's skip flags (the OD reproduction flag set); NIO uses stock
# Surefire — no testorder fork — plus -Dmaven.test.failure.ignore so a failing wrapper
# still prints its summary line for parsing.
NIO_RUN_FLAGS = (
    "-Drat.skip -Dcheckstyle.skip -Denforcer.skip=true -Dspotbugs.skip "
    "-Dmaven.test.failure.ignore=true -Djacoco.skip -Danimal.sniffer.skip "
    "-Dmaven.antrun.skip -Dspotless.check.skip"
).split()


# ---------------------------------------------------------------- row parsing

def load_nio_rows(test_config):
    """All `nio` rows. Columns (0-indexed): test=line[5], module=line[3],
    iterations=line[6], java=line[8], url=line[10]. Unlike OD there is no polluter
    (col 4) and unlike ID there is no nondexSeed (col 9)."""
    rows = []
    with open(test_config, newline="") as f:
        for line in csv.reader(f):
            if len(line) < 11 or line[0].strip().lower() != "nio":
                continue
            rows.append({
                "container": line[1].strip(),
                "zip_id": line[2].strip(),
                "module": line[3].strip() or ".",
                "test": line[5].strip(),        # Class#method (the single flaky test)
                "iterations": line[6].strip() or "10",
                "java": line[8].strip() or "8",
                "url": line[10].strip(),
            })
    return rows


# ------------------------------------------------------------------ wrapper

def nio_wrapper_names(victim):
    """Derive the wrapper identifiers from the victim ('pkg.Class#method' or dotted).
    Kept in lock-step with repair_NIO.nio_wrapper_names so the driver and the repair
    engine agree on the wrapper name/location (standard Maven layout)."""
    if "#" in victim:
        victim_class, victim_method = victim.split("#", 1)
    else:
        victim_class = ".".join(victim.split(".")[:-1])
        victim_method = victim.split(".")[-1]
    pkg = ".".join(victim_class.split(".")[:-1])
    victim_class_simple = victim_class.split(".")[-1]
    method_cap = victim_method[0].upper() + victim_method[1:] if victim_method else victim_method
    wrapper_simple = method_cap + "NioReproTest"
    wrapper_fqcn = (pkg + "." + wrapper_simple) if pkg else wrapper_simple
    return pkg, victim_class_simple, victim_method, wrapper_simple, wrapper_fqcn


def nio_wrapper_source(pkg, wrapper_simple, victim_class_simple, victim_method):
    lines = []
    if pkg:
        lines.append("package " + pkg + ";")
        lines.append("")
    lines += [
        "// AUTO-GENERATED by FlakyDoctor for NIO reproduction -- DO NOT EDIT.",
        "// Invokes " + victim_class_simple + "#" + victim_method + " twice in the same JVM (full",
        "// JUnit lifecycle each time). A non-idempotent test passes the first run and fails the",
        "// second; the fix target is the victim test, NOT this wrapper.",
        "import org.junit.Test;",
        "import org.junit.Assert;",
        "import org.junit.runner.JUnitCore;",
        "import org.junit.runner.Request;",
        "import org.junit.runner.Result;",
        "",
        "public class " + wrapper_simple + " {",
        "    @Test public void runTwice() throws Exception {",
        "        Request req = Request.method(" + victim_class_simple + ".class, \"" + victim_method + "\");",
        "        Result r1 = new JUnitCore().run(req);",
        "        Assert.assertTrue(\"first invocation should pass: \" + r1.getFailures(), r1.wasSuccessful());",
        "        Result r2 = new JUnitCore().run(req);",
        "        Assert.assertTrue(\"second invocation should pass (NIO assertion): \" + r2.getFailures(), r2.wasSuccessful());",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def write_nio_wrapper(project_dir, module, victim):
    """Generate the wrapper at <module>/src/test/java/<pkg>/<Wrapper>.java (the victim's
    own package). Idempotent, and matches where repair_NIO writes it (next to the victim),
    so at most one wrapper exists. Called after the git baseline so it stays untracked."""
    pkg, victim_class_simple, victim_method, wrapper_simple, wrapper_fqcn = nio_wrapper_names(victim)
    parts = [project_dir]
    if module and module != ".":
        parts.append(module)
    parts += ["src", "test", "java"] + (pkg.split(".") if pkg else []) + [wrapper_simple + ".java"]
    wrapper_path = os.path.join(*parts)
    if not os.path.exists(wrapper_path):
        os.makedirs(os.path.dirname(wrapper_path), exist_ok=True)
        with open(wrapper_path, "w") as fh:
            fh.write(nio_wrapper_source(pkg, wrapper_simple, victim_class_simple, victim_method))
        rf.log(f"generated NIO wrapper {wrapper_fqcn} at {wrapper_path}")
    else:
        rf.log(f"NIO wrapper already present at {wrapper_path}")
    return wrapper_fqcn


# --------------------------------------------------------- reproduce (wrapper)

def nio_test_result(output):
    """Mirror repair_NIO/analyze_nio_test_result for the single-test wrapper totals line."""
    if re.search(r"Tests run: 1, Failures: 0, Errors: 0, Skipped: 0", output):
        return "test_pass"
    if re.search(r"Tests run: 1, (Failures: 1, Errors: 0|Failures: 0, Errors: 1), Skipped: 0", output):
        return "test_failure"
    if "COMPILATION ERROR" in output:
        return "compilation_error"
    return "build_failure"


def reproduce_with_nio_wrapper(container_dir, project_dir, module, wrapper_fqcn, jdk):
    """Run the generated wrapper (victim twice in one JVM). Gate: the wrapper test must
    FAIL — i.e. the victim passes its first invocation and fails the second — so the NIO
    flake reproduces. Zero API cost."""
    rf.log(f"reproducing with the NIO wrapper {wrapper_fqcn}#runTwice (victim run twice in one JVM)")
    env = rf.maven_env(container_dir, jdk)
    cmd = ["mvn", "test", "-pl", module, f"-Dtest={wrapper_fqcn}#runTwice"] + NIO_RUN_FLAGS
    try:
        res = subprocess.run(cmd, cwd=project_dir, env=env,
                             capture_output=True, text=True, timeout=1800)
    except subprocess.TimeoutExpired:
        rf.die("NIO wrapper run timed out after 30 min")
    out = res.stdout + ("\n" + res.stderr if res.stderr else "")
    if "BUILD FAILURE" in out and "Tests run:" not in out:
        rf.die("could not build/run the NIO wrapper (last lines):\n"
               + "\n".join(out.splitlines()[-15:]))
    result = nio_test_result(out)
    rf.log(f"  result: {result}")
    if result == "test_failure":
        rf.log("NIO FLAKE REPRODUCED — the victim fails on its second invocation in the same JVM")
        return
    if result == "test_pass":
        rf.die("the wrapper passed (the victim is idempotent in this environment) — NIO flake "
               "did not reproduce here; not spending API calls.")
    rf.die(f"unexpected wrapper result '{result}' — check the build (last lines):\n"
           + "\n".join(out.splitlines()[-15:]))


# ------------------------------------------------------------------- repair

def run_flakydoctor_nio(container_dir, row, github_url, project_name, projects_dir,
                        api_key, model, jdk):
    zip_base = os.path.basename(container_dir)
    _, test_dotted = rf.split_test(row["test"])
    url = github_url or f"https://github.com/agentflake/{project_name}"
    if url.rstrip("/").split("/")[-1] != project_name:
        rf.die(f"staged dir name '{project_name}' must equal the URL's last segment ({url})")

    out_dir = os.path.join("outputs", f"af_fd_nio_{zip_base}_{time.strftime('%Y%m%d_%H%M%S')}")
    os.makedirs(out_dir, exist_ok=True)
    input_csv = os.path.join(out_dir, "input.csv")
    # repair_NIO input format: project,sha,module,test,test_type,status,pr,notes
    with open(input_csv, "w") as f:
        f.write(f"{url},{zip_base},{row['module']},{test_dotted},NIO,,,\n")

    env = rf.maven_env(container_dir, jdk)
    cmd = ["python3", "-u", "src/flakydoctor.py",
           "--input-tests-csv", input_csv,
           "--flakiness-type", "NIO",
           "--projects", projects_dir,
           "--api-key", api_key,
           "--model", model,
           "--output-dir", out_dir,
           "--output-result-csv", os.path.join(out_dir, "results.csv"),
           "--output-result-json", os.path.join(out_dir, "results.json"),
           "--output-details-json", os.path.join(out_dir, "details.json")]
    rf.log(f"running FlakyDoctor ({model}, NIO); live output follows, artifacts in {out_dir}/")
    rf.clean_m2_markers(container_dir)  # clear cached remote-failure markers before verify
    rf.run_flakydoctor_cmd(cmd, env, out_dir)
    return out_dir


def summarize_nio(out_dir, container_dir):
    results = os.path.join(out_dir, "results.json")
    if not os.path.exists(results):
        rf.log("no results.json produced — check the run output above")
        return
    raw = open(results).read().strip()
    if not raw:
        rf.log("results.json is empty — FlakyDoctor produced no verdict (check output above)")
        return
    dec, idx = json.JSONDecoder(), 0
    while idx < len(raw):
        obj, end = dec.raw_decode(raw, idx)
        idx = end
        while idx < len(raw) and raw[idx] in " \n\t,":
            idx += 1
        tr = obj.get("test_results", {})
        fixed = any(v == "test_pass" for v in tr.values())
        print()
        rf.log(f"test    : {obj.get('victim') or obj.get('test')}")
        rf.log(f"rounds  : {tr}")
        rf.log(f"fixed   : {'YES' if fixed else 'NO'}")
        rf.log(f"patch   : {obj.get('patch_file')}")
        if obj.get("Exceptions"):
            rf.log(f"exceptions: {obj['Exceptions']}")
    dev_fix = os.path.join(container_dir, "Fixed.patch")
    if os.path.exists(dev_fix):
        rf.log(f"developer's reference fix for comparison: {dev_fix}")


# --------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--test-config", default="test_config.csv", help="path to test_config.csv (default: test_config.csv in the FlakyDoctor root)")
    ap.add_argument("--container", help="result_container name (col 2) of the nio row to run")
    ap.add_argument("--list", action="store_true", help="list nio rows")
    ap.add_argument("--api-key", help="Anthropic API key (required unless --skip-repair)")
    ap.add_argument("--model", default="Claude", help="FlakyDoctor model (default: Claude)")
    ap.add_argument("--projects", default="projects", help="FlakyDoctor projects dir")
    ap.add_argument("--skip-repair", action="store_true", help="stop after reproducing (zero API cost)")
    ap.add_argument("--keep-zip", action="store_true", help="keep the downloaded zip in /tmp")
    ap.add_argument("--fresh", action="store_true",
                    help="remove any existing staged container and re-download + rebuild "
                         "from pristine source (use when re-running an already-repaired container)")
    ap.add_argument("--strip-snapshot", action="store_true",
                    help="rewrite <version>X-SNAPSHOT</version> -> X in every pom.xml after "
                         "staging, so inter-module deps resolve against the RELEASE artifacts "
                         "cached in the staged .m2")
    args = ap.parse_args()

    if not os.path.exists("src/flakydoctor.py"):
        rf.die("run this from the FlakyDoctor root (src/flakydoctor.py not found)")

    rows = load_nio_rows(args.test_config)
    if not rows:
        rf.die(f"no nio rows found in {args.test_config}")

    if args.list:
        print(f"{'container':55} java  test")
        for r in rows:
            print(f"{r['container']:55} {r['java']:5} {r['test']}")
        return

    if not args.container:
        rf.die("--container is required (use --list to see options)")
    matches = [r for r in rows if r["container"] == args.container]
    if not matches:
        rf.die(f"no nio row with result_container == {args.container}")
    row = matches[0]

    if not args.skip_repair and not args.api_key:
        rf.die("--api-key is required (or pass --skip-repair to stop after reproduction)")

    container_dir, project_dir, project_name, github_url = \
        rf.stage_container(row, args.projects, keep_zip=args.keep_zip, fresh=args.fresh)
    rf.ensure_git_baseline(project_dir)
    if args.strip_snapshot:
        # after the baseline so the rewrite is committed (survives FlakyDoctor's git stash)
        rf.strip_snapshot_versions(project_dir)
    # Generate the wrapper AFTER the baseline commit so it stays untracked and survives
    # FlakyDoctor's per-round `git stash` / `git checkout <victim>`.
    wrapper_fqcn = write_nio_wrapper(project_dir, row["module"], row["test"])
    jdk = rf.build_project(container_dir, project_dir, row["module"], row["java"])
    reproduce_with_nio_wrapper(container_dir, project_dir, row["module"], wrapper_fqcn, jdk)

    if args.skip_repair:
        rf.log("--skip-repair: stopping after successful reproduction.")
        return

    out_dir = run_flakydoctor_nio(container_dir, row, github_url, project_name,
                                  args.projects, args.api_key, args.model, jdk)
    summarize_nio(out_dir, container_dir)
    rf.generate_semantic_diff(out_dir)
    rf.remove_flaky_m2(container_dir)
    rf.prune_container_dir(container_dir)


if __name__ == "__main__":
    main()
